server:
  port: 8888
  servlet:
    context-path: /demo
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://tiny.db.elephantsql.com:5432/meqdgper
    username: meqdgper
    password: 03tb3aiKhz3LFde8SPK9Ws2miDhSRzsm
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher